version: "3.8"

services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080 # Bind host port 3000 to container port 8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  nginx:
    build:
      context: ./backend
      dockerfile: Dockerfile.nginx
    container_name: nginx
    depends_on:
      - open-webui
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
      - /c/Certs/ThrallOperator/ssl:/etc/ssl/thralloperator:ro # Mount certificate directory
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
